import type { Metadata } from "next";
import { Geist, Geist_Mono, Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav";
import { Suspense } from "react";
import ProductLoading from "./(i-tech)/shop/loading";
import { ThemeProvider } from "@/components/theme-provider";

const getKantumruy = Kantumruy_Pro({
  variable: "--font-kantumruy",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${getKantumruy.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {" "}
          <div className=" bg-white dark:bg-gray-800 ">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
