import type { Metadata } from "next";
import { Geist, Geist_Mono, Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav";

const getKantumruy = Kantumruy_Pro({
  variable: "--font-kantumruy",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${getKantumruy.className} ${geistSans.variable} ${geistMono.variable} antialiased bg-blue-900 `}
      >
        <Navbar />
        <div className="bg-blue-900  ">{children}</div>
      </body>
    </html>
  );
}
